server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bugtracker_db
    username: postgres
    password: Colloccollo123#
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/minibugtracker